import Banner from '@/src/components/Banner/Banner'
import CardsBrigadeiros from '@/src/components/CardsBrigadeiros/CardsBrigadeiros'
import Texto from '@/src/components/Texto/Texto'
import Head from 'next/head'
import Header from '../src/components/Header/Header'
import { useEffect } from "react";
import AOS from 'aos';
import 'aos/dist/aos.css';

export default function Home() {
  useEffect(() => {
    AOS.init({
    offset: 110,
    startEvent: 'DOMContentLoaded',
    initClassName: 'aos-init',
    animatedClassName: 'aos-animate'
    });
    }, [])
    
  return (
    <>
      <Head>
        <title>Disk Brigadeiro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <Banner />
      <Texto texto="Nossos Brigadeiros" />
      <CardsBrigadeiros />
    </>
  )
}
